language: cpp

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

env:
  global:
   - NODE_VERSION: "0.10"

matrix:
  include:
     - env: TESTCASE='./testcases/90-50-7' OPTIONS="--null-bridge --threadpool=8"
     - env: TESTCASE='./testcases/90-50-7-tiled-lzw' OPTIONS="--null-bridge --threadpool=8"
     - env: TESTCASE='./testcases/L7' OPTIONS="--null-bridge --threadpool=8"
     # - env: TESTCASE='./testcases/blank-compressed' OPTIONS="--threadpool=8"

before_install:
 - source ./scripts/install_node.sh ${NODE_VERSION}

install:
 - ./install.sh

before_script:
 - ${TESTCASE}/setup.sh

script:
 - ./bench.sh
