language: cpp

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

env:
  global:
   - NODE_VERSION: "0.10"

matrix:
  include:
     - env: TESTCASE='./test/fixtures/us-counties-polygon.geojson' OPTIONS="--threadpool=8"

before_install:
 - source ./scripts/install_node.sh ${NODE_VERSION}

install:
 - ./scripts/install.sh

script:
 - npm test
 - ./bin/bench.js ${TESTCASE} latest ${OPTIONS}
