environment:
  matrix:
    - nodejs_version: 0.10.33
      msvs_toolset: 14
      platform: x64

shallow_clone: true

install:
  # find and remove default node.exe to avoid conflicts
  - node -e "console.log(process.execPath)" > node_path.txt
  - SET /p NODE_EXE_PATH=<node_path.txt
  - del node_path.txt
  - del /q /s "%NODE_EXE_PATH%"
  - SET PATH=%CD%;%PATH%;
  - SET ARCHPATH=
  - if %platform% == x64 (SET ARCHPATH=x64/)
  - if "%msvs_toolset%" == "12" powershell Install-Product node $env:nodejs_version $env:platform
  - if "%msvs_toolset%" == "14" powershell Write-Output "fetching https://mapbox.s3.amazonaws.com/node-cpp11/v$env:nodejs_version/${env:ARCHPATH}node.exe"
  - if "%msvs_toolset%" == "14" powershell Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/v$env:nodejs_version/${env:ARCHPATH}node.exe"
  - powershell Write-Output "https://mapbox.s3.amazonaws.com/node-cpp11/vcredist_$env:platform.exe"
  - powershell Start-FileDownload "https://mapbox.s3.amazonaws.com/node-cpp11/vcredist_$env:platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm install
  - cd testcases/L7/
  - ps: Start-FileDownload https://springmeyer.s3.amazonaws.com/LE70460262003149EDC00-RGB.tif
  - cd ../../mapnik-versions/v3.2.0
  - npm install
  - cd ../../
  - cd ../../mapnik-versions/v3.4.0
  - npm install
  - cd ../../
  - node test.js testcases/L7/map.xml mapnik-versions/v3.2.0/
  - node test.js testcases/L7/map.xml mapnik-versions/v3.4.0/

build: off
test: off
deploy: off